#!/usr/bin/env python2
def jobstring(mpi_num=1):
    ####################################################
    ####################################################
    #                 EDIT HERE                        #
    # The PBS header of the script that is submitted   #
    pbs="""
#
#SBATCH --mem=1000
#SBATCH --time=03:30:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=martin.bergemann@monash.edu
#SBATCH --partition=batch
"""
    if mpi_num > 2:
        pbs="""
%s
#SBATCH --ntasks=%i
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#
#
"""%(pbs,mpi_num)
    else:
        pbs="""
        %s
#
#"""%(pbs)
#
# The modules to be loaded and the path var's      #
    modules="""
. /etc/profile
module load python/2.7.12-gcc
module load hdf5
module load netcdf
module unload openmpi
module load openmpi/1.10.2-gcc
#
#Export all paths we need
export OMP_NUM_THREADS=1
export I_MPI_FABRICS=tmi
export I_MPI_PMI_LIBRARY=/usr/mpi/gcc/mvapich2-2.1/lib/libmpi.so
tmp=$(echo "$HOME/Software/lib/python2.7/site-packages:$PYTHONPATH")
tmp=$(echo "${tmp}:/opt/sw/python-2.7.5/lib/python2.7/site-packages/")
export PYTHONPATH=${tmp}:$HOME/Programming
export PATH=$HOME/Software/bin:$PATH
#
"""
    # The submit command for the batch system (qsub or llsubmit)
    # If you want to be emailed by the system, include these in job_string:
    #PBS -M your_email@address
    #PBS -m abe  # (a = abort, b = begin, e = end)
    #submitcmd = 'screen -d -m -S inter bash -c'
    submitcmd = 'sbatch'
    return pbs,modules,submitcmd,mpi_num

##########################################################
#########################################################
# Example PBS cluster job submission in Python

import time,os,string,stat,sys
from datetime import datetime, timedelta as td
from Master.configdir import Config
import numpy as np
from run_cloudmodel import *




def main(fyear,lyear,itterator='--boxes=None',ad_vars=[],
        out=os.path.join(os.environ['HOME'],'jobs_smcm'),
        python='/usr/local/python/2.7.12-gcc/bin/python'):
    
    
    pbs,modules,submitcmd,mpi_num = jobstring()
    if not os.path.isfile(python):
        for path in os.environ["PATH"].split(":"):
            if os.path.isfile(os.path.join(path,'python')):
                python = os.path.join(path,'python')

    if not fyear.startswith('--'):
        fyear = '--start=%s'%fyear
    if not lyear.startswith('--'):
        lyear = '--end=%s'%lyear

    #if not os.path.isdir(os.path.join(out,'error')):
    #    os.makedirs(os.path.join(out,'error'))
    #if not os.path.isdir(os.path.join(out,'output')):
    #    os.makedirs(os.path.join(out,'output'))

    for nn,i in enumerate(itterator):
        # Open a pipe to the qsub command.
        #Edit: opening a STDIN pipe with os.popen and pip
        #the entry to qsub doesn't work here 
        #Therefore a tmp-script is created that will be executed
        script = os.path.join(os.environ['HOME'],'tmp_%03i.sh'%nn)
        output = open(script,'w')
     
        # Customize your options here
        if i.startswith('--seed'):
            fyear,lyear='',''
        if len(ad_vars):
            Config='"%s %s %s %s"' %(fyear,lyear,i,' '.join(ad_vars))
        else:
            Config='"%s %s %s"' %(fyear,lyear,i)
        f=fyear.split('=')[-1]
        l=lyear.split('=')[-1]
        v=i.split('=')[-1].split(',')[0]
        job_name = "smcm_%s_%s_%s" %(v,f,l)
        command =os.path.abspath(\
                os.path.join(os.path.dirname(__file__),'run_cloudmodel.py'))
        sys.stdout.flush()
        sys.stdout.write('Submitting script for %s %s\n'\
                %(command,Config.replace('"','')))
        job_string = """#!/bin/bash
#
%s
#SBATCH --output=%s/%s.out
#SBATCH --error=%s/%s.err
#SBATCH --job-name=%s
#Make module available
%s
export PYTHONDONTWRITEBYTECODE=True
#Run the Script
#
config=%s
script="%s"
let num=%i
if [ $num -gt 1 ];then
    cmd="mpirun -n %i $script $config "
else
    cmd="$script $config "
fi
$cmd
    """   % (pbs, out, job_name,out, job_name,job_name,modules,Config,\
            python+' '+command,mpi_num,mpi_num)
        #Write job_string to script and close it
        output.write(job_string)
        output.close()
        #Make script executables
        os.chmod(script, os.stat(script).st_mode | stat.S_IEXEC)
        #Send script to cluster with qsub and delete it
        os.system("%s %s 1> /dev/null" %(submitcmd,script))
        
        os.remove(script)
        # Print your job and the response to the screen
        time.sleep(0.1)







if __name__ == '__main__':
    out=os.path.join(os.environ['HOME'],'jobs_smcm')
    kwargs = kw()
    helpstring='''submit v1.0 Martin Bergemann 13 Jan 2015
    Copyrith (c) 2013 through 2015, Martin Bergemann
    submit comes with ABSOLUTELY NO WARRANTY; for details type submit -w



    Usage:
    submit startdate enddate [options]

    Dates:
          The dates representing the start and end dates for the download
          the format of the dates must be YYYY-MM-DD


    Options:
          --out:     the directory name where the std-out and std-err should be
                     written to [default %s]
          --w:       print the copying policy
          all other keywords variables are passed to the script, the variables are:
        Variables:
            start (str)     : The start of the integration (dafualt %s)
            end   (str)     : The end of the integration (default %s)
            boxes   (list)  : The name of the boxes that are considered (default %s)
            J0  (nd-array)  : The interaction potential (default %s)
            seed (list)     : The random number generator seed (default %s)
    Example:
        The comand
        submit 1998-01-01 1998-01-02  --boxes=coast_03
        submits a job for running the cloud model from 1st to 2nd of Jan 199 in the
        boxes coast_03
    '''%(
            out,
            str(kwargs['end']),
            str(kwargs['end']),
            str(kwargs['boxes']),
            str(kwargs['J0']),
            str(kwargs['seed'])
            )


    if len(sys.argv) < 2:
        sys.exit(helpstring)
    years=sys.argv[1:3]
    ad_vars = [] #Additional variables to be passed to run_cloudmodel
    itterator=['--boxes=None']
    try:
        for arg in sys.argv[3:]:
            if arg.lower().startswith('--h') or arg.lower().startswith('-h'):
                sys.exit(helpstring)
            elif arg.lower().startswith('-w') or arg.lower().startswith('-w'):
                l=open('LICENSE').read().replace('XXX','submit')
                sys.stdout.flush()
                sys.stdout.write(l+'\n')
                sys.exit()
            elif arg.lower().startswith('--out') or arg.lower().startswith('-o'):
                out=arg.split('=')[-1]
            else:
                if not arg.lower().startswith('--boxes') and not arg.lower().startswith('--seed'):
                    ad_vars.append(arg)
                elif arg.lower().startswith('--seed'):
                    itterator=['--seed=%s'%(i) for i in arg.split('=')[-1].split(',')]
                else:
                    itterator=['--boxes=%s'%(i) for i in arg.split('=')[-1].split(',')]
    except IndexError:
        pass
    if  len(years) == 2:
        fyear = '--start=%s'%years[0]
        lyear = '--end=%s'%years[-1]
    else:
        sys.exit(helpstring)
    main(fyear,lyear,itterator=itterator,ad_vars=ad_vars,out=out)

